# Generated by Django 4.2.6 on 2023-10-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrocket',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstage',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rocket',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalrocket',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
