# Generated by Django 4.2.6 on 2023-10-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0002_historicalrocket_code_historicalstage_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='rocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='rocket.rocket'),
        ),
    ]
